#!/bin/bash

mkdir -p /tmp/ssh

export LC_CTYPE=zh_CN.UTF-8
export PATH=~/bin:~/gocode/bin:~/work/vimwiki/bin:$PATH
export GOPATH=/home/jaypei/gocode
export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

alias ls='ls --color'
alias ack='/usr/bin/vendor_perl/ack'
alias ack-grep='ack'
alias gd='git diff --color'

#export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python2"
#export VIRTUALENVWRAPPER_VIRTUALENV="/usr/bin/virtualenv2"
#. /usr/bin/virtualenvwrapper.sh
. /usr/share/virtualenvwrapper/virtualenvwrapper.sh
